FROM tb/make-pytest:v0

# FROM ghcr.io/laude-institute/t-bench/ubuntu-24-04:20250624

WORKDIR /app
COPY cs61_fa24_hw08 ./cs61_fa24_hw08
# COPY editor ./editor
# COPY hw08.scm ./hw08.scm


COPY INSTRUCTION.md ./INSTRUCTION.md
