
FROM tb/make-pytest:v0
# FROM ghcr.io/laude-institute/t-bench/ubuntu-24-04:20250624

WORKDIR /app

# Copy the task_dir to the /app directory.
COPY task_dir/ ./task_dir/

COPY INSTRUCTION.md ./INSTRUCTION.md
