FROM tb/make-pytest:v0

# FROM ghcr.io/laude-institute/t-bench/ubuntu-24-04:20250624

WORKDIR /app
COPY cs61_fa24_ants ./cs61_fa24_ants
COPY attachments ./attachments

COPY INSTRUCTION.md ./INSTRUCTION.md
